server:
  port: 8080

spring:
  profiles:
    active: ${spring.profiles.active}
  servlet:
    multipart:
      maxFileSize: "100MB"
      maxRequestSize: "100MB"
  mvc:
    async:
      request-timeout: 300000

file:
  resourceLocation: /fileService

